name: CI

on:
  push:
    branches:
    - master

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: push gh-pages
      run: git subtree push --prefix publish origin gh-pages
