name: Verify PR

on:
  pull_request:
   
jobs:
  build:
    name: Verify build 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Setup node 
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install 
     
      - name: Lint 
        run: |
          npm run lint --if-present

      - name: Test
        run: |
          npm run test --if-present

      - name: Build 
        run: |
          npm run build 
        env:
          NODE_ENV: production 

      # - name: Get package version 
      #   id: get_version 
      #   uses: bbonkr/get-version-action@v1.0.3
      #   with:
      #     project: "./package.json"

      - name: Add comment 
        uses: unsplash/comment-on-pr@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          OUTPUT: "✅ This pull request is verified to build."
        with:
          msg: ${{ env.OUTPUT }}
          check_for_duplicate_msg: false